apiVersion: apps/v1
kind: Deployment
metadata:
  name: foot-app
  namespace: footapp  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foot-app
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: foot-app
    spec:
      containers:
      - name: foot-app
        image: arindambanerjee/footapp:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: MY_SECRET
          valueFrom:
           secretKeyRef:
            name: footapp-secret
            key: MY_SECRET
#        - name: PLATFORM
#          valueFrom:
#           configMapKeyRef:
#            name: footapp-cm
#            key: PLATFORM
        livenessProbe:
            httpGet:
                path: /
                port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 30
        readinessProbe:
            httpGet:
                path: /
                port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 30
      serviceAccountName: user-robot
      automountServiceAccountToken: false
---
apiVersion: v1
kind: Service
metadata:
  name: foot-app
  namespace: footapp
spec:
  type: LoadBalancer
  ports:
   - protocol: TCP
     port: 80
     targetPort: 8080
  selector:
    app: foot-app