kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gl-psp-clusterrole # General pod security policy
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - general-psp
  verbs:
  - use